<?php
/**
 * Demo content for `wp lampandpath seed`, taken from docs/design/homepage.html.
 *
 * Writers, bios, article bodies and the extra verses are placeholders for the
 * demo site; titles, excerpts and dates follow the design. Dates are relative
 * to the day the seed runs, so the homepage always looks current.
 *
 * @package Lampandpath_Core
 */

defined( 'ABSPATH' ) || exit;

return array(

	// Illustrations rendered from the design, in seed/images/.
	'images'  => array(
		'when-god-feels-silent' => __( 'Sunrise over green hills and a winding path, seen through a window', 'lampandpath-core' ),
		'rest-is-not-a-reward'  => __( 'A crescent moon and stars over calm water at night', 'lampandpath-core' ),
		'raising-kids-who-pray' => __( 'A small house with warm lit windows among trees', 'lampandpath-core' ),
		'peace-that-guards'     => __( 'A leafy branch against a pale green circle', 'lampandpath-core' ),
		'faith-on-a-monday'     => __( 'Town rooftops and a church spire under a morning sun', 'lampandpath-core' ),
		'praying-the-psalms'    => __( 'An open book with a gold ribbon bookmark', 'lampandpath-core' ),
	),

	// Writers, keyed by login. "about" is the About section order (0 = not shown).
	'writers' => array(
		'grace.villanueva' => array(
			'first' => 'Grace',
			'last'  => 'Villanueva',
			'role'  => 'editor',
			'title' => 'Editor',
			'color' => 'green',
			'about' => 1,
			'bio'   => 'Grace edits Lamp & Path and writes about prayer, waiting and hope.',
		),
		'samuel.reyes'     => array(
			'first' => 'Samuel',
			'last'  => 'Reyes',
			'role'  => 'author',
			'title' => 'Pastor and writer',
			'color' => 'blue',
			'about' => 2,
			'bio'   => 'Samuel is a pastor who writes about rest, work and the rhythms of faith.',
		),
		'hannah.lim'       => array(
			'first' => 'Hannah',
			'last'  => 'Lim',
			'role'  => 'author',
			'title' => 'Family and parenting',
			'color' => 'amber',
			'about' => 3,
			'bio'   => 'Hannah writes about family life and helping kids grow in faith.',
		),
		'daniel.okafor'    => array(
			'first' => 'Daniel',
			'last'  => 'Okafor',
			'role'  => 'author',
			'title' => 'Bible teacher',
			'color' => 'violet',
			'about' => 4,
			'bio'   => 'Daniel teaches the Bible and writes about reading Scripture well.',
		),
		'ruth.mendoza'     => array(
			'first' => 'Ruth',
			'last'  => 'Mendoza',
			'role'  => 'author',
			'title' => 'Writer',
			'color' => 'rose',
			'about' => 0,
			'bio'   => 'Ruth writes about faith at work and in ordinary places.',
		),
		'micah.torres'     => array(
			'first' => 'Micah',
			'last'  => 'Torres',
			'role'  => 'author',
			'title' => 'Writer',
			'color' => 'green',
			'about' => 0,
			'bio'   => 'Micah writes about prayer and the Psalms.',
		),
	),

	// "Where are you today?" collections.
	'needs'   => array(
		'anxious'               => array(
			'name'  => 'I’m anxious',
			'text'  => 'Peace for racing thoughts and restless nights.',
			'verse' => 'Philippians 4:6–7',
			'icon'  => 'waves',
		),
		'grieving'              => array(
			'name'  => 'I’m grieving',
			'text'  => 'Honest laments and the hope of resurrection.',
			'verse' => 'Psalm 34:18',
			'icon'  => 'candle',
		),
		'new-to-faith'          => array(
			'name'  => 'I’m new to faith',
			'text'  => 'Who Jesus is and what it means to follow him.',
			'verse' => 'John 3:16',
			'icon'  => 'sprout',
		),
		'pray-more'             => array(
			'name'  => 'I want to pray more',
			'text'  => 'Simple, practical ways to build a daily prayer life.',
			'verse' => 'Mark 1:35',
			'icon'  => 'sunrise',
		),
		'struggling-to-forgive' => array(
			'name'  => 'I’m struggling to forgive',
			'text'  => 'What forgiveness is, what it isn’t, and where to begin.',
			'verse' => 'Colossians 3:13',
			'icon'  => 'unlock',
		),
		'far-from-god'          => array(
			'name'  => 'I feel far from God',
			'text'  => 'For seasons of doubt, dryness, and waiting on God.',
			'verse' => 'Psalm 13:1',
			'icon'  => 'path',
		),
	),

	// Articles: the hero, the 5 latest articles and the 5 "Most read" articles.
	'posts'   => array(
		array(
			'slug'     => 'when-god-feels-silent',
			'title'    => 'When God feels silent: learning to trust in the waiting',
			'excerpt'  => 'Silence isn’t the same as absence. What Psalm 13 teaches about honest prayer, stubborn hope, and the God who hears even when we can’t hear him.',
			'author'   => 'grace.villanueva',
			'category' => 'faith-and-doubt',
			'tags'     => array( 'grief' ),
			'needs'    => array( 'far-from-god', 'grieving' ),
			'days_ago' => 1,
			'minutes'  => 8,
			'image'    => 'when-god-feels-silent',
			'sticky'   => true,
			'views'    => 150,
		),
		array(
			'slug'     => 'rest-is-not-a-reward',
			'title'    => 'Rest is not a reward: rediscovering the Sabbath',
			'excerpt'  => 'God built rest into creation before we’d done a day’s work. Maybe it was never ours to earn.',
			'author'   => 'samuel.reyes',
			'category' => 'christian-living',
			'tags'     => array( 'worship', 'work-and-calling' ),
			'needs'    => array( 'far-from-god' ),
			'days_ago' => 3,
			'minutes'  => 6,
			'image'    => 'rest-is-not-a-reward',
			'views'    => 90,
		),
		array(
			'slug'     => 'raising-kids-who-love-to-pray',
			'title'    => 'Raising kids who love to pray',
			'excerpt'  => 'Low-pressure ways to make prayer feel like home for kids, from toddlers to teenagers.',
			'author'   => 'hannah.lim',
			'category' => 'family',
			'tags'     => array( 'parenting' ),
			'needs'    => array( 'pray-more' ),
			'days_ago' => 6,
			'minutes'  => 6,
			'image'    => 'raising-kids-who-pray',
			'views'    => 70,
		),
		array(
			'slug'     => 'the-peace-that-guards-your-heart',
			'title'    => 'The peace that guards your heart: Philippians 4 and anxiety',
			'excerpt'  => 'Paul isn’t scolding anxious people. He’s extending an invitation, and it comes with a promise.',
			'author'   => 'daniel.okafor',
			'category' => 'hope-and-healing',
			'tags'     => array( 'anxiety' ),
			'needs'    => array( 'anxious' ),
			'days_ago' => 8,
			'minutes'  => 9,
			'image'    => 'peace-that-guards',
			'views'    => 120,
		),
		array(
			'slug'     => 'faith-on-a-monday',
			'title'    => 'Faith on a Monday: why your ordinary work matters to God',
			'excerpt'  => 'Classrooms, kitchens, job sites, spreadsheets. Ordinary work is one way we love God and neighbor.',
			'author'   => 'ruth.mendoza',
			'category' => 'faith-and-work',
			'tags'     => array( 'work-and-calling' ),
			'needs'    => array(),
			'days_ago' => 10,
			'minutes'  => 5,
			'image'    => 'faith-on-a-monday',
			'views'    => 40,
		),
		array(
			'slug'     => 'praying-the-psalms',
			'title'    => 'Praying the Psalms when you don’t have the words',
			'excerpt'  => 'God’s people have prayed these 150 songs for thousands of years. Here’s how to make them yours.',
			'author'   => 'micah.torres',
			'category' => 'prayer',
			'tags'     => array( 'worship', 'grief' ),
			'needs'    => array( 'pray-more', 'grieving' ),
			'days_ago' => 13,
			'minutes'  => 7,
			'image'    => 'praying-the-psalms',
			'views'    => 60,
		),
		array(
			'slug'     => 'how-to-read-the-bible',
			'title'    => 'How to read the Bible when you don’t know where to start',
			'excerpt'  => 'Start small, start with a Gospel, and bring your questions. A simple way to begin reading Scripture for yourself.',
			'author'   => 'daniel.okafor',
			'category' => 'bible-study',
			'tags'     => array( 'new-believers' ),
			'needs'    => array( 'new-to-faith' ),
			'days_ago' => 34,
			'minutes'  => 7,
			'views'    => 480,
		),
		array(
			'slug'     => 'ten-verses-to-pray-when-anxious',
			'title'    => 'Ten verses to pray when you’re anxious',
			'excerpt'  => 'Short passages to pray slowly when worry won’t let go, from the Psalms to Paul’s letters.',
			'author'   => 'grace.villanueva',
			'category' => 'devotionals',
			'tags'     => array( 'anxiety' ),
			'needs'    => array( 'anxious', 'pray-more' ),
			'days_ago' => 38,
			'minutes'  => 4,
			'views'    => 390,
		),
		array(
			'slug'     => 'what-does-it-mean-to-abide-in-christ',
			'title'    => 'What does it mean to abide in Christ?',
			'excerpt'  => 'Jesus’ picture of the vine and the branches, and what staying close to him looks like on an ordinary day.',
			'author'   => 'samuel.reyes',
			'category' => 'devotionals',
			'tags'     => array( 'new-believers' ),
			'needs'    => array( 'new-to-faith' ),
			'days_ago' => 42,
			'minutes'  => 8,
			'views'    => 310,
		),
		array(
			'slug'     => 'forgiveness-isnt-forgetting',
			'title'    => 'Forgiveness isn’t forgetting: a biblical look',
			'excerpt'  => 'Forgiving someone doesn’t mean pretending it didn’t happen. What Scripture says about forgiveness, trust and healing.',
			'author'   => 'daniel.okafor',
			'category' => 'bible-study',
			'tags'     => array( 'forgiveness', 'marriage' ),
			'needs'    => array( 'struggling-to-forgive' ),
			'days_ago' => 47,
			'minutes'  => 9,
			'views'    => 260,
		),
		array(
			'slug'     => 'finding-a-church-home',
			'title'    => 'Finding a church home after a move',
			'excerpt'  => 'Visiting new churches can feel lonely. Practical steps for finding a community to belong to, and to serve.',
			'author'   => 'hannah.lim',
			'category' => 'christian-living',
			'tags'     => array( 'new-believers' ),
			'needs'    => array( 'new-to-faith' ),
			'days_ago' => 53,
			'minutes'  => 6,
			'views'    => 190,
		),
	),

	// Verses of the day (King James Version, public domain). "day" is days from today.
	'verses'  => array(
		array(
			'slug'       => 'lamentations-3-22-23',
			'title'      => 'Lamentations 3:22–23',
			'chapter'    => 'Lamentations 3',
			'day'        => 0,
			'text'       => '<sup>22</sup>It is of the LORD’s mercies that we are not consumed, because his compassions fail not. <sup>23</sup>They are new every morning: great is thy faithfulness.',
			'reflection' => 'A question to carry today: where have you seen God’s faithfulness this week, even in something small?',
		),
		array(
			'slug'       => 'psalm-46-1',
			'title'      => 'Psalm 46:1',
			'chapter'    => 'Psalm 46',
			'day'        => 1,
			'text'       => '<sup>1</sup>God is our refuge and strength, a very present help in trouble.',
			'reflection' => 'A question to carry today: what trouble are you carrying alone that you could bring to God?',
		),
		array(
			'slug'       => 'isaiah-40-31',
			'title'      => 'Isaiah 40:31',
			'chapter'    => 'Isaiah 40',
			'day'        => 2,
			'text'       => '<sup>31</sup>But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
			'reflection' => 'A question to carry today: where do you need strength to keep going rather than to start over?',
		),
		array(
			'slug'       => 'matthew-11-28',
			'title'      => 'Matthew 11:28',
			'chapter'    => 'Matthew 11',
			'day'        => 3,
			'text'       => '<sup>28</sup>Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
			'reflection' => 'A question to carry today: what would it look like to rest in Jesus, not just from your work?',
		),
		array(
			'slug'       => 'romans-8-28',
			'title'      => 'Romans 8:28',
			'chapter'    => 'Romans 8',
			'day'        => 4,
			'text'       => '<sup>28</sup>And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
			'reflection' => 'A question to carry today: how has God brought good out of something hard in your past?',
		),
		array(
			'slug'       => 'philippians-4-6-7',
			'title'      => 'Philippians 4:6–7',
			'chapter'    => 'Philippians 4',
			'day'        => 5,
			'text'       => '<sup>6</sup>Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. <sup>7</sup>And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
			'reflection' => 'A question to carry today: which worry can you turn into a prayer right now?',
		),
		array(
			'slug'       => 'proverbs-3-5',
			'title'      => 'Proverbs 3:5',
			'chapter'    => 'Proverbs 3',
			'day'        => 6,
			'text'       => '<sup>5</sup>Trust in the LORD with all thine heart; and lean not unto thine own understanding.',
			'reflection' => 'A question to carry today: where are you leaning on your own understanding?',
		),
		array(
			'slug'       => 'john-14-27',
			'title'      => 'John 14:27',
			'chapter'    => 'John 14',
			'day'        => 7,
			'text'       => '<sup>27</sup>Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.',
			'reflection' => 'A question to carry today: how is the peace Jesus gives different from the peace the world offers?',
		),
	),

	// Reading plans, in homepage order.
	'plans'   => array(
		array(
			'slug'     => 'the-gospel-of-mark',
			'title'    => 'The Gospel of Mark',
			'excerpt'  => 'Meet Jesus in the shortest, fastest-moving Gospel, one chapter a day.',
			'overview' => 'Read one chapter of Mark each day for 16 days. Each reading takes about ten minutes.',
			'minutes'  => 10,
			'book'     => 'Mark',
			'chapters' => range( 1, 16 ),
		),
		array(
			'slug'     => 'proverbs-for-the-month',
			'title'    => 'Proverbs for the month',
			'excerpt'  => 'Wisdom for work, words, money, and friendship. One chapter a day.',
			'overview' => 'Proverbs has 31 chapters, one for each day of a long month. Start today and read one chapter a day.',
			'minutes'  => 10,
			'book'     => 'Proverbs',
			'chapters' => range( 1, 31 ),
		),
		array(
			'slug'     => 'psalms-for-anxious-hearts',
			'title'    => 'Psalms for anxious hearts',
			'excerpt'  => 'Psalms that name fear honestly and answer it with trust.',
			'overview' => 'Fourteen psalms for anxious seasons, from laments to songs of trust. Read slowly, and pray the words back to God.',
			'minutes'  => 15,
			'book'     => 'Psalm',
			'chapters' => array( 3, 4, 13, 23, 27, 31, 34, 37, 42, 46, 56, 91, 121, 139 ),
		),
	),

	// Prayer requests. Empty name = "Shared anonymously"; the pending one tests moderation.
	'prayers' => array(
		array(
			'slug'      => 'seed-prayer-marisol',
			'name'      => 'Marisol',
			'consent'   => true,
			'text'      => 'Please pray for my mom. She has surgery on Friday morning and she’s scared.',
			'hours_ago' => 2,
			'prayed'    => 12,
			'status'    => 'publish',
		),
		array(
			'slug'      => 'seed-prayer-jun',
			'name'      => 'Jun',
			'consent'   => true,
			'text'      => 'I start a new job on Monday after eight months of searching. Pray that I’d work with integrity and joy.',
			'hours_ago' => 5,
			'prayed'    => 8,
			'status'    => 'publish',
		),
		array(
			'slug'      => 'seed-prayer-small-group',
			'name'      => '',
			'consent'   => true,
			'text'      => 'Our small group is helping a family who lost their home in the floods. Pray for provision and rest for them.',
			'hours_ago' => 26,
			'prayed'    => 21,
			'status'    => 'publish',
		),
		array(
			'slug'      => 'seed-prayer-pending',
			'name'      => 'Ana',
			'consent'   => false,
			'text'      => 'Please pray for wisdom as I care for my dad this month.',
			'hours_ago' => 1,
			'prayed'    => 0,
			'status'    => 'pending',
		),
	),
);
